#!/usr/bin/env python3
"""Generate and verify data/locale/*.ini from tools/locales.json.

tools/locales.json is the single source of truth for every user-visible string.
Before this, the generator carried its own copy of the key list, which fell four
releases behind what the .ini files actually shipped: running it would have
silently deleted every string added since — a tool in the repository that
introduced a regression when used.

Usage:
    python tools/gen_locales.py            # rewrite data/locale/*.ini
    python tools/gen_locales.py --check    # verify, change nothing (CI)

--check fails when:
  * a shipped .ini differs from what the table would generate
  * a locale is missing a key another locale has
  * a key used in the C++ sources is missing from the table
  * a key in the table is used nowhere (a string nobody can ever see, and nine
    translations of it to maintain)
  * a translation drops a %1/%2 placeholder its English text uses
  * a file is not UTF-8, or carries a BOM
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLE = ROOT / "tools" / "locales.json"
LOCALE_DIR = ROOT / "data" / "locale"
SRC_DIRS = [ROOT / "src" / "plugin", ROOT / "src" / "core"]

HEADER = "# Generated by tools/gen_locales.py from tools/locales.json - do not edit by hand.\n"

# Keys as the C++ side asks for them.
USED_KEY = re.compile(r'(?:obs_module_text|T)\("([A-Za-z0-9_.]+)"\)')
# The end-of-clip table names its keys as plain strings in a struct.
TABLE_KEY = re.compile(r'"(OnEnd(?:Tip)?\.[A-Za-z0-9_]+)"')
PLACEHOLDER = re.compile(r"%\d")


def load() -> tuple[list[str], dict[str, dict[str, str]]]:
    data = json.loads(TABLE.read_text(encoding="utf-8"))
    return data["locales"], data["keys"]


def render(locale: str, keys: dict[str, dict[str, str]]) -> str:
    out = [HEADER, "\n"]
    previous_group = None
    for key, values in keys.items():
        group = key.split(".")[0]
        if previous_group is not None and group != previous_group:
            out.append("\n")
        previous_group = group
        text = values.get(locale, values["en-US"])
        out.append(f'{key}="{text}"\n')
    return "".join(out)


def used_keys() -> set[str]:
    found: set[str] = set()
    for directory in SRC_DIRS:
        for path in sorted(directory.rglob("*")):
            if path.suffix not in {".cpp", ".hpp"}:
                continue
            text = path.read_text(encoding="utf-8")
            found.update(USED_KEY.findall(text))
            found.update(TABLE_KEY.findall(text))
    return found


def check(locales: list[str], keys: dict[str, dict[str, str]]) -> int:
    problems: list[str] = []

    for key, values in keys.items():
        english = values["en-US"]
        wanted = set(PLACEHOLDER.findall(english))
        for locale in locales:
            if locale not in values:
                problems.append(f"{locale}: missing key {key}")
                continue
            got = set(PLACEHOLDER.findall(values[locale]))
            if got != wanted:
                problems.append(
                    f"{locale}: {key} uses {sorted(got) or 'no placeholders'}, "
                    f"English uses {sorted(wanted) or 'none'}"
                )

    used = used_keys()
    for key in sorted(used - set(keys)):
        problems.append(f"key used in the sources but not translated: {key}")
    for key in sorted(set(keys) - used):
        problems.append(f"key translated but used nowhere: {key}")

    for locale in locales:
        path = LOCALE_DIR / f"{locale}.ini"
        if not path.exists():
            problems.append(f"{locale}: {path.name} is missing")
            continue
        raw = path.read_bytes()
        if raw.startswith(b"\xef\xbb\xbf"):
            problems.append(f"{locale}: file starts with a UTF-8 BOM")
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            problems.append(f"{locale}: not valid UTF-8 ({exc})")
            continue
        if text != render(locale, keys):
            problems.append(f"{locale}: out of date - run python tools/gen_locales.py")

    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    if problems:
        print(f"{len(problems)} problem(s) found", file=sys.stderr)
        return 1
    print(f"ok: {len(keys)} keys x {len(locales)} locales")
    return 0


def write(locales: list[str], keys: dict[str, dict[str, str]]) -> int:
    LOCALE_DIR.mkdir(parents=True, exist_ok=True)
    for locale in locales:
        path = LOCALE_DIR / f"{locale}.ini"
        # newline="" keeps LF endings on Windows too: OBS reads these as UTF-8
        # text, and the repository stores them with LF.
        path.write_text(render(locale, keys), encoding="utf-8", newline="")
    print(f"wrote {len(locales)} locale files ({len(keys)} keys each)")
    return 0


def main() -> int:
    locales, keys = load()
    if "--check" in sys.argv:
        return check(locales, keys)
    return write(locales, keys)


if __name__ == "__main__":
    raise SystemExit(main())
